version: 2.1
jobs:
    test-and-lint:
      docker: 
        - image: circleci/node:14-bullseye-browsers
      steps:
        - checkout
        - run: 
            name: Run Style linter
            command: yarn lint:stylelint
        - run:
            name: Run Eslint
            command: yarn lint:eslint
        - run: 
            name: Run Tests
            command: yarn test --passWithNoTests
    deploy-to-dev:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy
            command: ${SERVER_CONNECTION_COMMAND} 'source ~/.nvm/nvm.sh; cd /var/www/builds/front-dev; git pull origin dev; yarn; yarn build;'
        - run:
            name: Release
            command: ${SERVER_CONNECTION_COMMAND} 'cp -r /var/www/builds/front-dev/build/. /var/www/dev0' 
    deploy-to-prod:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy to prod
            command: ${SERVER_CONNECTION_COMMAND} 'source ~/.nvm/nvm.sh; cd /var/www/builds/front; git pull origin master; yarn; yarn build;'
            environment:
              SENTRY_DSN: ${REACT_APP_SENTRY_DSN}
        - run:
            name: Release
            command: ${SERVER_CONNECTION_COMMAND} 'cp -r /var/www/builds/front/build/. /var/www/app' 
    deploy-to-demo:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy to demo
            command: ${SERVER_CONNECTION_COMMAND} 'source ~/.nvm/nvm.sh; cd /var/www/builds/demo; git pull origin demo; yarn; yarn build;'
        - run:
            name: Release
            command: ${SERVER_CONNECTION_COMMAND} 'cp -r /var/www/builds/demo/build/. /var/www/demo' 
workflows:
  version: 2
  preparing:
    jobs:
      - test-and-lint:
          pre-steps:
            - checkout
            - run: 
                command: yarn
          filters:
            branches:
              ignore: master
  deployment:
    jobs:
      - hold:
          type: approval
      - deploy-to-demo:
          filters:
            branches:
              only:
                - demo 
      - deploy-to-dev:
          filters:
            branches:
              only: 
                - dev
              ignore: master
      - deploy-to-prod:
          requires: 
            - hold
          filters:
            branches:
              only: master
              ignore: dev


    
      
