version: 2.1
jobs:
    test-and-lint:
      docker: 
        - image: circleci/node:14-bullseye-browsers-legacy
      steps:
        - checkout
        - run: 
            name: Run Style linter
            command: npm lint:stylelint
        - run:
            name: Run Eslint
            command: npm lint:eslint
        - run: 
            name: Run Tests
            command: npm test
    
    deploy-to-dev:
      deploy:
        machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy
            command: bash ./deploy.sh
workflows:
  version: 2
  preparing:
    jobs:
      - test-and-lint:
          filters:
            branches:
              ignore: master
  deployment:
    jobs:
      - deploy-to-dev:
          filters:
            branches:
              only: dev


    
      
