version: 2.1
jobs:
    test-and-lint:
      docker: 
        - image: circleci/node:14-bullseye-browsers-legacy
      steps:
        - checkout
        #need to move it to pre-scripts
        - run: 
            name: Run Style linter
            command: yarn lint:stylelint
        - run:
            name: Run Eslint
            command: yarn lint:eslint
        - run: 
            name: Run Tests
            command: yarn test --passWithNoTests
    deploy-to-dev:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy
            command: bash ./deploy.sh
workflows:
  version: 2
  preparing:
    jobs:
      - test-and-lint:
          pre-steps:
            - run: 
                command: yarn
          filters:
            branches:
              ignore: master
  deployment:
    jobs:
      - deploy-to-dev:
          filters:
            branches:
              only: dev


    
      
