version: 2.1
jobs:
    test-and-lint:
      docker: 
        - image: circleci/node:14-bullseye-browsers
      steps:
        - checkout
        - run: 
            name: Run Style linter
            command: yarn lint:stylelint
        - run:
            name: Run Eslint
            command: yarn lint:eslint
        - run: 
            name: Run Tests
            command: yarn test --passWithNoTests
    build-app:
      docker:
        - image: circleci/node:14-bullseye-browsers
      working_directory: /tmp/app/
      steps:
        - checkout
        - run:
            name: Create Artifacts
            environment:
              CI: "false"
            command: yarn && yarn build
        - store_artifacts:
            path: /tmp/app
    deploy-to-dev:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy
            command: |
                    ${SERVER_CONNECTION_COMMAND} 'source ~/.nvm/nvm.sh; cd /var/www/dev0; git pull origin dev; yarn; yarn build;'
    deploy-to-prod:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy to prod
            command: |
                    ${SERVER_CONNECTION_COMMAND} 'source ~/.nvm/nvm.sh; cd /var/www/app; git pull origin master; yarn; yarn build;'
workflows:
  version: 2
  preparing:
    jobs:
      - test-and-lint:
          pre-steps:
            - checkout
            - run: 
                command: yarn
          filters:
            branches:
              ignore: master
  deployment:
    jobs:
      - build-app:
          filters:
            branches:
              only:
                - cicd-piplines
      - hold:
          type: approval
      - deploy-to-dev:
          requires:
            - build-app
          filters:
            branches:
              only: 
                - dev
                - cicd-piplines
              ignore: master
      - deploy-to-prod:
          requires: 
            - hold
            - build-app
          filters:
            branches:
              only: master
              ignore: dev


    
      
