version: 2.1
jobs:
    test-and-lint:
      docker: 
        - image: circleci/node:14-bullseye-browsers-legacy
      steps:
        - checkout
        #need to move it to pre-scripts
        - run: 
            name: install deps
            command: npm install
        - run: 
            name: Run Style linter
            command: npm run lint:stylelint
        - run:
            name: Run Eslint
            command: npm run lint:eslint
        - run: 
            name: Run Tests
            command: npm run test
    deploy-to-dev:
      machine:
        enabled: true
      steps:
        - checkout
        - run:
            name: Deploy
            command: bash ./deploy.sh
workflows:
  version: 2
  preparing:
    jobs:
      - test-and-lint:
          filters:
            branches:
              ignore: master
  deployment:
    jobs:
      - deploy-to-dev:
          filters:
            branches:
              only: dev


    
      
