name: Run on dev
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Build Artifacts
        uses: actions/checkout@v3

      - name: Init Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Up Caches
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Generate deployable artifacts
        env:
          REACT_APP_POSTHOG_API_KEY: ${{ secrets.POSTHOG_DEV_API_KEY }}
          REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_DEV_API_KEY }}
        run: |
          yarn
          yarn run prei18n:extract
          yarn run i18n:extract
          yarn run i18n:compile
          CI=false yarn build
      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: build
          retention-days: 1
  deploy:
    needs: build
    name: Deploy to Dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Extract Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: ~/build
      - name: Deploy to host
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/build
          remote: /var/www/dev0
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
