name: Run on dev
on: 
  push:
    branches:
      - "dev"
jobs:
  deploy:
    name: Dev deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
      - name: Release
      
