name: Push Worfklow

on:
  push:
    branches-ignore:
      - "master"
      - "dev"
      - "test"
      - "demo"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Check packages integrity
        run: yarn check --integrity

      - name: Eslint
        run: yarn lint:eslint

      - name: Stylelint for CSS Modules
        run: yarn lint:stylelint

      - name: Build ts
        run: CI=false yarn build
