name: Release app
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: cp -r /var/www/test/. /var/www/app


