name: Run on test
on: 
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: source ~/.nvm/nvm.sh; cd /var/www/builds/test; git pull origin master; yarn; yarn run prei18n:extract; yarn run i18n:extract; yarn run i18n:compile; yarn build;
          
      - name: Release
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: cp -r /var/www/builds/test/build/. /var/www/test
