name: Run on test
on: 
  push:
    branches:
      - "test"

jobs:
  deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
      - name: Release